/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prolab3_banking_project.view;

import prolab3_banking_project.serviceImpl.ManagerLoginServiceImpl;
import prolab3_banking_project.session.ManagerSession;

/**
 *
 * @author Ali Erkin
 */
public class MudurAnaMenu1 extends javax.swing.JFrame {

    private ManagerLoginServiceImpl loginService = new ManagerLoginServiceImpl();
    /**
     * Creates new form MudurAnaMenu
     */
    public MudurAnaMenu1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dovizIslemleri = new javax.swing.JButton();
        maaşBelirle = new javax.swing.JButton();
        sistemİlerlet = new javax.swing.JButton();
        musteriEkle = new javax.swing.JButton();
        faizİşlemleri = new javax.swing.JButton();
        genelDurum = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dovizIslemleri.setText("Döviz İşlemleri");
        dovizIslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dovizIslemleriActionPerformed(evt);
            }
        });

        maaşBelirle.setText("Maaş Belirle");
        maaşBelirle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maaşBelirleActionPerformed(evt);
            }
        });

        sistemİlerlet.setText("Sistemi İlerlet");
        sistemİlerlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistemİlerletActionPerformed(evt);
            }
        });

        musteriEkle.setText("Müşteri Ekle");
        musteriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriEkleActionPerformed(evt);
            }
        });

        faizİşlemleri.setText("Faiz İşlemleri");
        faizİşlemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faizİşlemleriActionPerformed(evt);
            }
        });

        genelDurum.setText("Genel Durum Görüntüle");
        genelDurum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genelDurumActionPerformed(evt);
            }
        });

        logout.setText("Çıkış");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(genelDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dovizIslemleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maaşBelirle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(musteriEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sistemİlerlet, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(faizİşlemleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(genelDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dovizIslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(maaşBelirle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(sistemİlerlet, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(musteriEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(faizİşlemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musteriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriEkleActionPerformed
        this.setVisible(false);
        new MudurMusteriEkle().setVisible(true);
        ManagerSession.getParentFrame().add(this);
    }//GEN-LAST:event_musteriEkleActionPerformed

    private void dovizIslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dovizIslemleriActionPerformed
        this.setVisible(false);
        new MudurDovizIslemleri().setVisible(true);
        ManagerSession.getParentFrame().add(this);
    }//GEN-LAST:event_dovizIslemleriActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        ManagerSession.getParentFrame().get(ManagerSession.getParentFrame().size()-1).setVisible(true);
        ManagerSession.getParentFrame().remove(ManagerSession.getParentFrame().size()-1);
        loginService.logout();
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void maaşBelirleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maaşBelirleActionPerformed
        this.setVisible(false);
        new MudurMaasBelirle().setVisible(true);
        ManagerSession.getParentFrame().add(this);
    }//GEN-LAST:event_maaşBelirleActionPerformed

    private void genelDurumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genelDurumActionPerformed
        this.setVisible(false);
        new MudurGenelDurum().setVisible(true);
        ManagerSession.getParentFrame().add(this);
    }//GEN-LAST:event_genelDurumActionPerformed

    private void sistemİlerletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistemİlerletActionPerformed
        this.setVisible(false);
        new MudurSistemİlerlet().setVisible(true);
        ManagerSession.getParentFrame().add(this);
    }//GEN-LAST:event_sistemİlerletActionPerformed

    private void faizİşlemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faizİşlemleriActionPerformed
        this.setVisible(false);
        new MudurFaizİslemleri().setVisible(true);
        ManagerSession.getParentFrame().add(this);
    }//GEN-LAST:event_faizİşlemleriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MudurAnaMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MudurAnaMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MudurAnaMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MudurAnaMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MudurAnaMenu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dovizIslemleri;
    private javax.swing.JButton faizİşlemleri;
    private javax.swing.JButton genelDurum;
    private javax.swing.JButton logout;
    private javax.swing.JButton maaşBelirle;
    private javax.swing.JButton musteriEkle;
    private javax.swing.JButton sistemİlerlet;
    // End of variables declaration//GEN-END:variables
}
